<a href="https://colab.research.google.com/github/sahil-randhe/DS_LAB-/blob/main/dsl_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#using numpy

print("Enter the elements of the 3x3 matrix:")

matrix = []

for i in range(3):
    row = list(map(float, input(f"Enter row {i+1} (3 numbers separated by space): ").split()))
    matrix.append(row)

# Convert list to NumPy array
matrix = np.array(matrix)

# Compute determinant
determinant = np.linalg.det(matrix)

print("\nMatrix:")
print(matrix)

print("\nDeterminant:", determinant)


Enter the elements of the 3x3 matrix:
Enter row 1 (3 numbers separated by space): 9 8 5
Enter row 2 (3 numbers separated by space): 5 5 5
Enter row 3 (3 numbers separated by space): 3 1 1

Matrix:
[[9. 8. 5.]
 [5. 5. 5.]
 [3. 1. 1.]]

Determinant: 30.000000000000004


In [ ]:
print("Enter the elements of the 3x3 matrix:")

matrix = []

for i in range(3):
    row = list(map(float, input(f"Enter row {i+1} (3 numbers separated by space): ").split()))
    matrix.append(row)

# Assign matrix elements
a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

# Determinant formula
determinant = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

print("\nMatrix:")
for row in matrix:
    print(row)

print("\nDeterminant:", determinant)


Enter the elements of the 3x3 matrix:
Enter row 1 (3 numbers separated by space): 9 8 5
Enter row 2 (3 numbers separated by space): 5 5 5
Enter row 3 (3 numbers separated by space): 3 1 1 

Matrix:
[9.0, 8.0, 5.0]
[5.0, 5.0, 5.0]
[3.0, 1.0, 1.0]

Determinant: 30.0


In [ ]:
#without using numpy

print("Enter the elements of the 3x3 matrix:")

matrix = []
for i in range(3):
    row = list(map(float, input(f"Enter row {i+1} (3 numbers separated by space): ").split()))
    matrix.append(row)

# Convert to NumPy array
matrix = np.array(matrix)

print("\nMatrix:")
print(matrix)

# Check determinant
determinant = np.linalg.det(matrix)

if determinant == 0:
    print("\nInverse does not exist (determinant is 0).")
else:
    inverse = np.linalg.inv(matrix)
    print("\nInverse of the matrix:")
    print(inverse)


Enter the elements of the 3x3 matrix:
Enter row 1 (3 numbers separated by space): 9 8 5
Enter row 2 (3 numbers separated by space): 5 5 5
Enter row 3 (3 numbers separated by space): 3 1 1

Matrix:
[[9. 8. 5.]
 [5. 5. 5.]
 [3. 1. 1.]]

Inverse of the matrix:
[[ 0.         -0.1         0.5       ]
 [ 0.33333333 -0.2        -0.66666667]
 [-0.33333333  0.5         0.16666667]]


In [ ]:
print("Enter the elements of the 3x3 matrix:")

matrix = []
for i in range(3):
    row = list(map(float, input(f"Enter row {i+1} (3 numbers separated by space): ").split()))
    matrix.append(row)

a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

# Determinant of the matrix
det = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

print("\nMatrix:")
for row in matrix:
    print(row)

if det == 0:
    print("\nInverse does not exist (determinant is 0).")
else:
    # Cofactor matrix
    C = [
        [(e*i - f*h), -(d*i - f*g), (d*h - e*g)],
        [-(b*i - c*h), (a*i - c*g), -(a*h - b*g)],
        [(b*f - c*e), -(a*f - c*d), (a*e - b*d)]
    ]

    # Adjoint (transpose of cofactor matrix)
    adjoint = [
        [C[0][0], C[1][0], C[2][0]],
        [C[0][1], C[1][1], C[2][1]],
        [C[0][2], C[1][2], C[2][2]]
    ]

    # Inverse = (1/det) * adjoint
    inverse = [[adjoint[r][c] / det for c in range(3)] for r in range(3)]

    print("\nInverse of the matrix:")
    for row in inverse:
        print(row)


Enter the elements of the 3x3 matrix:
Enter row 1 (3 numbers separated by space): 9 8 5
Enter row 2 (3 numbers separated by space): 5 5 5
Enter row 3 (3 numbers separated by space): 1 1 3

Matrix:
[9.0, 8.0, 5.0]
[5.0, 5.0, 5.0]
[1.0, 1.0, 3.0]

Inverse of the matrix:
[1.0, -1.9, 1.5]
[-1.0, 2.2, -2.0]
[0.0, -0.1, 0.5]


In [ ]:
#without using numpy
# Given equations:
# 1) 2x + 3y = 10
# 2) 4x + 5y = 20

# Multiply equation (1) by 2 to get a common coefficient for x:
# 3) 4x + 6y = 20

# Subtract equation (2) from equation (3):
# (4x + 6y) - (4x + 5y) = 20 - 20
# y = 0

y = 0

# Substitute y = 0 into equation (1):
# 2x + 3(0) = 10
# 2x = 10
# x = 5

x = (10 - 3 * y) / 2

print("The solution for x and y is:")
print(f"x = {x:.2f}")
print(f"y = {y:.2f}")

The solution for x and y is:
x = 5.00
y = 0.00


In [ ]:


# Define the coefficient matrix A
A = np.array([[2, 3], [4, 5]])

# Define the constant vector B
B = np.array([10, 20])

# Solve the system of linear equations
x_and_y = np.linalg.solve(A, B)

print("The solution for x and y is:")
print(f"x = {x_and_y[0]:.2f}")
print(f"y = {x_and_y[1]:.2f}")

The solution for x and y is:
x = 5.00
y = 0.00


In [ ]:
#using numpy
# Given equations:
# 1) 2x + 3y = 10
# 2) 4x + 5y = 20

# Multiply equation (1) by 2 to get a common coefficient for x:
# 3) 4x + 6y = 20

# Subtract equation (2) from equation (3):
# (4x + 6y) - (4x + 5y) = 20 - 20
# y = 0

y = 0

# Substitute y = 0 into equation (1):
# 2x + 3(0) = 10
# 2x = 10
# x = 5

x = (10 - 3 * y) / 2

print("The solution for x and y is:")
print(f"x = {x:.2f}")
print(f"y = {y:.2f}")

The solution for x and y is:
x = 5.00
y = 0.00
